### PR TITLE
Figma project

### PR DESCRIPTION
**Pull request by Jordan-Tamrat**

### CODE REVIEW

**Review by DawitSishu — CHANGES_REQUESTED** [review]
### Changes Requested:
Screenshot_2024-01-08_13-37-28

## This is your Work so Please include the missing images

**Comment by Jordan-Tamrat** [comment]
Fixed!

**Review by DawitSishu — CHANGES_REQUESTED** [review]
### Minor Issues:

Screenshot_2024-01-08_14-21-26
## As you can see there's unncessary spacing above the text in the navbar please remove that
 
### optional changes:
Screenshot_2024-01-08_14-23-54

##As shown in the code you are usiong px , try using % or vh or vw as they'll be more efficient when adding huge responsive paddings and heights, try to incorporate them if you want to make your design more responsive

**Comment by Jordan-Tamrat** [comment]
I did because the design u sent us it have space above the text but if it is unnecessary I will remove it

**Comment by Jordan-Tamrat** [comment]
I updated the navbar also about the "px" thing I will change it for next designs

**Review by DawitSishu — APPROVED** [review]
# Pull Request Ready for Merge! 🚀

7E2d


Your hard work and dedication have paid off! 🎉 The pull request you've been working on is now ready and approved for merging. Fantastic job! 🙌

Take a moment to savor this accomplishment, and when you're ready, feel free to merge the pull request. If you have any questions or if there's anything else you'd like to discuss, I'm here!

Cheers to your success! 🥳

**Comment by Jordan-Tamrat** [comment]
Awesome, thank you so much!

**Pull request merged**
